/*
 * Author: Laith Oudah
 * University: Luleå Tekniska Universitet
 * Course: L0002B
 * LTU: LAIOUD-1
 * Assignment: Inlämningsuppgift 1
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace FormsAppUppgift1
{

    // Auto generated by Visual Studio 

    public class Program
    {
        [STAThread]
        static void Main(string[] args)
        {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Window());
        }
    }
}
